[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && cd proyecto_portafolio && python manage.py collectstatic --noinput"

[deploy]
startCommand = "cd proyecto_portafolio && gunicorn proyecto_portafolio.wsgi --bind 0.0.0.0:$PORT --log-file -"
